### ISSUE TITLE
Static 32-bit binaries don't work: https://www.feralhosting.com/faq/view?question=245

### ISSUE THREAD

**Issue by feralhosting** [feralhosting/feralfilehosting#11]
Submitted by: _Lemon_
From channel: #feral
At 2014-12-06 10:52:10 UTC

**Comment by feralhosting** [comment]
If the kernel version `3.2.0-4-amd64` you can use x86 binaries.

Do this command to check.

~~~
uname -r
~~~

**Comment by timelf123** [comment]
```
[gyges ~] uname -r
3.19.5-feral
```

Out of luck?
