### ISSUE TITLE
The install.syncthing produced an invalid .config/syncthing/config.xml

### ISSUE THREAD

**Issue by munkee** [feralhosting/feralfilehosting#26]
The line `syncport="(expr 1 + $appport)"` didn't work as intended and my `.config/syncthing/config.xml` contains 
```
   <options>
        <listenAddress>0.0.0.0:(expr 1 + 11469)</listenAddress>
```
which is obviously not what was intended. This causes syncthing to fail on startup and since it happens inside of screen it's not immediately obvious why.

**Comment by feralhosting** [comment]
Should be fixed with this:

https://github.com/feralhosting/feralfilehosting/commit/971d31d43115b8ef174f1a8d0aedc6b99257950e#diff-0384d684e90a239f50d50a0db63e3790R123

A typo introduced when updating the script.

Thank you for pointing it out.
