### ISSUE TITLE
Polybotes Apache Proxy/Vhost Problems

### ISSUE THREAD

**Issue by effinboy** [feralhosting/feralfilehosting#43]
Upon performing certain actions in automation scripts like Sickbeard, Apache will sometimes redirect to incorrect URLs. Updating to nginx resolved this issue for me with no additional configuration.

Example: 
Script running at http://polybotes.feralhosting.com/user/sickbeard/ will redirect to http://user.polybotes.feralhosting.com/user/sickbeard/

Although sickbeard is running at http://user.polybotes.feralhosting.com/sickbeard, Once vhost has been set for Sickbeard, and the webroot configured in the config.ini, you cannot use that URL, due to the script not loading all the page resources without the /user/sickbeard webroot.

Reproduction:
- Run Apache on a Polybotes slot
- Install Sickbeard using script from FAQ: https://www.feralhosting.com/faq/view?question=281
- Upon installation, add a show
- If you have not yet received an error, goto Manage > Mass Update, check edit for the show, and hit Edit selected
- Edit quality for the show and hit the blue submit button
- You should be incorrectly routed to a non-existing URL

Conjecture: 
The issue seems to arise when the user causes Sickbeard to write to it's sickbeard.db.
Something may be wrong with apache's current vhost/reverse proxy config. Now that I think about it, the issue could also be a mod_rewrite problem, but I'm no LAMP Stack expert.

**Comment by feralhosting** [comment]
Thank you for the issue. We will look into the apache proxypass configuration and see if the implementation needs to be fixed.
