### ISSUE TITLE
Download link to DokanSSHFS does not work

### ISSUE THREAD

**Issue by sanitas2** [feralhosting/feralfilehosting#51]
In this page:
https://github.com/feralhosting/feralfilehosting/tree/master/Feral%20Wiki/SSH/Mount%20Your%20Server%20as%20a%20Local%20Filesystem%20-%20Windows%20-%20Dokan%20-%20win-sshfs

**Comment by randomessence** [comment]
This link works, the rest are outdated and the article itself pretty much needs a facelift.

This where dokan is maintained now.

https://github.com/dokan-dev/dokany/releases

**Comment by randomessence** [comment]
This might be the only option for now:

https://github.com/dimov-cz/win-sshfs/releases
