### ISSUE TITLE
MONO install on feralhosting failing

### ISSUE THREAD

**Issue by nap2001** [feralhosting/feralfilehosting#59]
Scripts fail when setting up MONO. Specifically, the "make" command fails at the step which does a cd into the mcs directory and then runs:
`make --no-print-directory -s NO_DIR_CHECK=1 PROFILES='binary_reference_assemblies net_4_5 xbuild_12 xbuild_14    ' CC='gcc' all-profiles`

That step then fails with the following error messages: 
`make[3]: mcs: Command not found
build/profiles/basic.make:93: recipe for target 'build/deps/basic-profile-check.exe' failed
make[3]: *** [build/deps/basic-profile-check.exe] Error 127
*** The compiler 'mcs' doesn't appear to be usable.
*** You need Mono version 3.8 or better installed to build MCS
*** Check mono README for information on how to bootstrap a Mono installation.`

Any suggestions?

**Comment by feralhosting** [comment]
Don't use it. It probably needs to be updated.

You can use this instead.

    wget -qO ~/install.monoapps https://git.io/vzyZ4 && bash ~/install.monoapps

hosted here:

    https://github.com/userdocs/userdocs/tree/master/Remote_Programs/Mono/scripts

**Comment by nap2001** [comment]
Thank you. That seems to have addressed prior issue.
