### ISSUE TITLE
Automated Reroute - Stuck on Ubuntu 

### ISSUE THREAD

**Issue by reillyrenwick** [feralhosting/feralfilehosting#63]
Tried the script, gets stuck on:

You are currently using the default route
Testing single segment download speed from Default...

**Comment by frankthetank7254** [comment]
any chance your connection over the default route is just quite slow? the test download file is 200MB, so it can take some time, especially if your ISP doesn't like the default route I just successfully ran this script on debian, ubuntu, centos, and fedora, so i dont think the script is having an issue :)

**Comment by reillyrenwick** [comment]
Thanks frankthetank7254, you're completely right! Took over 45 minutes to download via the default route.

Cheers!
